version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/deploy-spring-boot-aws-eb-0.0.1-SNAPSHOT.war
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
    
