version: 0.2
phases:
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
  post_build:
    commands:
    - echo Build completed on `date`
    - mvn clean package
    - mv target/deploy-spring-boot-aws-eb-0.0.1-SNAPSHOT.war ./
artifacts:
  files:
  - deploy-spring-boot-aws-eb-0.0.1-SNAPSHOT.war