version: 0.2

phases:
    install:
        runtime-versions:
            java: openjdk8
    pre_build:
        commands:
            - echo CODEBUILD_RESOLVED_SOURCE_VERSION
    build:
        commands:
            - mvn compile
    post_build:
        commands:
            - mvn package
            - mkdir artifact   
            - unzip target/deploy-spring-boot-aws-eb-0.0.1-SNAPSHOT.war -d artifact/
artifacts:
    files:
        - artifact/**/*
    name: artifact