version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/deploy-spring-boot-aws-eb-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - deploy-spring-boot-aws-eb-0.0.1-SNAPSHOT.war
    - .ebextensions/**/*
 
